# 추후 Spring쪽으로 옮기기

version: "3.8"
services:
  # 배치서버
  batch-server:
    build:
      # context : 도커파일 위치
      # dockerfile : 도커파일 경로
      context: .
      dockerfile: Dockerfile-batch
    container_name: matches-collector
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    links:
      - mongodb
    env_file:
      - ./env/prod.env
      - ./env/common.env
    environment:
      - TZ=Asia/Seoul
    volumes:  
      - ./logs:/app/logs # 로컬 디렉토리 하위의 ./dev-data와 컨테이너 안의 /data/db를 매핑
  # 몽고DB
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:  
      - ./data:/data/db # 로컬 디렉토리 하위의 ./dev-data와 컨테이너 안의 /data/db를 매핑
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234 
      - MONGO_INITDB_DATABASE=LEAGUEDATA

  # Redis
  cachedb:
    image: redis
    container_name: cachedb
    labels:
        - "name=redis"
        - "mode=standalone"
    command: redis-server --port 6379
    ports:
      - 6379:6379
#     networks:
#       - privateNetwork

# networks:
#   privateNetwork:
#     driver: bridge